### ISSUE TITLE
Known bugs

### ISSUE THREAD

**Issue by RyanKung** [RingsNetwork/rings-fe#3]
- [x] 1.
- [ ] 2.
- [ ] 3.
- [x] 4. 

1. Address from ws should deduplicate here
![image](https://user-images.githubusercontent.com/662346/180619895-a98f39dc-3cab-4b84-a55b-ca9b2443683d.png)

**Comment by RyanKung** [comment]
2. memory leaks here.
![image](https://user-images.githubusercontent.com/662346/180622723-0ef91c1e-1312-46da-bfe7-71b09ce5cc6d.png)

* FrontEnd should not hold ref of Arc<Transport>, or we should use `std::sync::Weak`

related code.: 

`https://github.com/RingsNetwork/rings-fe/blob/master/contexts/RingsProvider.tsx#L15`
`https://github.com/RingsNetwork/rings-node/blob/master/src/browser/mod.rs#L349`

**Comment by googolmo** [comment]
@RyanKung https://github.com/RingsNetwork/rings-node/pull/240 try to fix the memory leaks issue

**Comment by RyanKung** [comment]
3. Fe should not panic here, if all nodes are offline, maybe a reconnect button?

![image](https://user-images.githubusercontent.com/662346/180645095-6a5dbb6a-540e-4dda-b907-17b325244c85.png)

**Comment by RyanKung** [comment]
4. After reconnect nodes, some connected node is not existed in swarm table.

![IMAGE 2022-07-24 22:44:39](https://user-images.githubusercontent.com/662346/180652391-403c534c-61a4-474d-9a69-9629eca73bcb.jpg)


![IMAGE 2022-07-24 22:44:12](https://user-images.githubusercontent.com/662346/180652363-d0c7f61b-f685-40b3-a8d9-79590a9c04dd.jpg)

**Comment by gaowhen** [comment]
1 is fixed [here](https://github.com/RingsNetwork/rings-fe/commit/59c26d679e74ad6f4d4d621bde85a2eed25f33c8).

**Comment by RyanKung** [comment]
> @RyanKung [RingsNetwork/rings-node#240](https://github.com/RingsNetwork/rings-node/pull/240) try to fix the memory leaks issue

Still not work, I modified Fe to print out all pending / peers

<img width="804" alt="image" src="https://user-images.githubusercontent.com/662346/180880089-98ce52b1-4eda-4c3e-886f-c7f03c9ef2a1.png">

And on console, we can see there is only few of them.

![image](https://user-images.githubusercontent.com/662346/180879975-841ed4fb-e2bd-4266-b84b-eaf33ef7f244.png)

But actually, on `chrome://webrtc-internals` and `about:webrtc` page, there is more than halv dozen connections.
![image](https://user-images.githubusercontent.com/662346/180879986-e7d9d1c3-7c3c-4620-a12b-f00301c094bb.png)
![image](https://user-images.githubusercontent.com/662346/180880214-291cad2a-0a29-45fb-98f9-35199f718990.png)
